name       : gnome-maps
version    : 3.36.1
release    : 31
source     :
    - https://download.gnome.org/sources/gnome-maps/3.36/gnome-maps-3.36.1.tar.xz : 1a32efd96ad898f77a636d2d0463d757009b4b812259c89ffdcb91d6afc052f9
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
