name       : gnome-maps
version    : 3.20.3
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-maps/3.20/gnome-maps-3.20.3.tar.xz : 055dbe0847c3f1c8fbdbf93d63896f41204642704c2b730e0bf01b7b82f09929
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
