name       : gnome-maps
version    : 3.36.4
release    : 33
source     :
    - https://download.gnome.org/sources/gnome-maps/3.36/gnome-maps-3.36.4.tar.xz : 1f56c5dc0581bc2f4321b6c37baf5727f331323ee8288298f494449f223d8ac6
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
