name       : gnome-maps
version    : 3.36.2
release    : 32
source     :
    - https://download.gnome.org/sources/gnome-maps/3.36/gnome-maps-3.36.2.tar.xz : 5ba219b9de98678cefa5848f6538db8dbd07f6c747fd43a99167a266878a9784
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
