name       : gnome-maps
version    : 3.32.1
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-maps/3.32/gnome-maps-3.32.1.tar.xz : 604615626bcb6acf41658b81977a41324fe5180a258c0e28f1c72806aec625e0
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
