name       : gnome-maps
version    : 3.34.0
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-maps/3.34/gnome-maps-3.34.0.tar.xz : 990b7f8cf7605a66efb01ab72ca18f6ca4d63f54261bb4b371bb96f97f10516f
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
