name       : gnome-maps
version    : 3.34.1
release    : 27
source     :
    - https://download.gnome.org/sources/gnome-maps/3.34/gnome-maps-3.34.1.tar.xz : 9a84bade4cd5762f28b951744cd7133d4992bf7c54343aa4c8f6630a8ce4da0e
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
