name       : gnome-maps
version    : 3.22.2
release    : 12
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-maps/3.22/gnome-maps-3.22.2.tar.xz : 1cc5c3a82fbb47435925c6268df220c0a788c9f6aa9054ae019e61c992d93948
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
