name       : gnome-maps
version    : 3.24.0
release    : 13
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-maps/3.24/gnome-maps-3.24.0.tar.xz : f4ab876c5cece1a897abe4a385967451bce8b7319c5eb540cc76d557a055da85
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
