name       : gnome-maps
version    : 3.24.1
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-maps/3.24/gnome-maps-3.24.1.tar.xz : eec390d56410d9cda9b1aed85016bbe24f5eaf7e1e0db7c45d5716c2112a4a0d
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
