name       : gnome-maps
version    : 3.28.1
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-maps/3.28/gnome-maps-3.28.1.tar.xz : a509a938cb8c255322916a1da7ac9fa633298c613b2c2e098c28335fc40ebda7
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
