name       : gnome-maps
version    : 3.38.1.1
release    : 34
source     :
    - https://download.gnome.org/sources/gnome-maps/3.38/gnome-maps-3.38.1.1.tar.xz : f3750370a709fe57ee2af3d0140429cbe81f88b4a02bd0f08c93faecb653a9f8
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
