name       : gnome-maps
version    : '42.2'
release    : 44
source     :
    - https://download.gnome.org/sources/gnome-maps/42/gnome-maps-42.2.tar.xz : 5e6d1b0ca7cc939ea91aadfda5633a865ea85fa5650036861b2bfef0bfd069b1
homepage   : https://wiki.gnome.org/Apps/Maps
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather4)
    - pkgconfig(libhandy-1)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
