name        : gnome-maps
version     : 3.18.2
release     : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-maps/3.18/gnome-maps-3.18.2.tar.xz : 693ff1559252eabe5d8c9c7354333b5aa1996e870936456d15706a0e0bac9278
license     : GPL-2.0+
summary     : GNOME Maps Application
description : |
    GNOME Maps Application
builddeps   :
    - pkgconfig(gjs-1.0)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(champlain-0.12)
rundeps     :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
