name       : gnome-maps
version    : 3.34.2
release    : 28
source     :
    - https://download.gnome.org/sources/gnome-maps/3.34/gnome-maps-3.34.2.tar.xz : c56d24e608c71dbf3447f977297c228aab81f7a9516cf7e8c35473082da3ba03
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
