name        : gnome-maps
version     : 3.16.2
release     : 5
source      :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-maps/3.16/gnome-maps-3.16.2.tar.xz : a7d791e4fb2dc3674232edf5c6d6112274869524db458695fc9fece49df07c96
homepage    : https://wiki.gnome.org/Apps/Maps
license     : GPL-2.0+
summary     : GNOME Maps Application
rundeps     :
    - gjs
    - gfbgraph
builddeps   :
    - pkgconfig(gjs-1.0)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(champlain-0.12)
description : |
    GNOME Maps Application
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
