name       : gnome-maps
version    : 3.26.1
release    : 17
source     :
    - https://download.gnome.org/sources/gnome-maps/3.26/gnome-maps-3.26.1.tar.xz : b92cd80ef37952ad8ce9c1526d1c632d7e7566539b1cb732bd6d304ba243815a
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
