name       : gnome-maps
version    : 3.24.2
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-maps/3.24/gnome-maps-3.24.2.tar.xz : e49a759678538f58c49845a7a77f97d409c55ae3c650c7ed1c0f8ba5e4842202
license    : GPL-2.0+
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
