name       : gnome-maps
version    : '42.0'
release    : 42
source     :
    - https://download.gnome.org/sources/gnome-maps/42/gnome-maps-42.0.tar.xz : 054486d3774073706a76a981417978d151be3b7224d723775bbe316efa2479df
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather4)
    - pkgconfig(libhandy-1)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %patch -p1 < $pkgfiles/0001-migrate-to-gweather4.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
