name       : gnome-maps
version    : '41.4'
release    : 41
source     :
    - https://download.gnome.org/sources/gnome-maps/41/gnome-maps-41.4.tar.xz : e340b13f46fe0b7d5b0f8f01413291ddcd870c74a5c38fa24cac1f585e70393e
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libhandy-1)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
