name        : gnome-maps
version     : 3.18.1
release     : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-maps/3.18/gnome-maps-3.18.1.tar.xz : 0f07bf1248705b9b78cd734f788c3d910e9bf34dff6c8595eda9fe1e13686ff9
license     : GPL-2.0+
summary     : GNOME Maps Application
rundeps     :
    - gjs
    - gfbgraph
builddeps   :
    - pkgconfig(gjs-1.0)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(folks)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(champlain-0.12)
description : |
    GNOME Maps Application
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
