name       : gnome-maps
version    : 3.32.2
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-maps/3.32/gnome-maps-3.32.2.tar.xz : dd9fab9e46405fc15f607992a74b8528afad3520220a8a0e21fd35d95dfb7cfb
license    : GPL-2.0-or-later
component  : office
summary    : GNOME Maps Application
description: |
    GNOME Maps Application
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(folks)
    - pkgconfig(gee-0.8)
    - pkgconfig(geoclue-2.0)
    - pkgconfig(geocode-glib-1.0)
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(rest-0.7)
rundeps    :
    - gjs
    - geoclue
    - gfbgraph
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
